{{- if .Values.conversionWebhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vitistack-crds.name" . }}-conversion-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vitistack-crds.labels" . | nindent 4 }}
    app.kubernetes.io/component: conversion-webhook
{{- end }}
