---
apiVersion: vitistack.io/v1alpha1
kind: MachineClass
metadata:
  name: best-effort-xlarge
spec:
  displayName: Best Effort xLarge
  description: Best-effort instance with 4 cores and 32Gi memory (Tanzu best-effort-xlarge)
  enabled: true
  default: false
  category: memory
  cpu:
    cores: 4
    sockets: 1
    threads: 1
  memory:
    quantity: 32Gi
  machineProviders: []
