---
apiVersion: vitistack.io/v1alpha1
kind: MachineClass
metadata:
  name: best-effort-2xlarge
spec:
  displayName: Best Effort 2XLarge
  description: Best-effort instance with 8 cores and 64Gi memory (Tanzu best-effort-2xlarge)
  enabled: true
  default: false
  category: Memory
  cpu:
    cores: 8
    sockets: 1
    threads: 1
  memory:
    quantity: 64Gi
  machineProviders: []
