---
apiVersion: vitistack.io/v1alpha1
kind: MachineClass
metadata:
  name: best-effort-medium
spec:
  displayName: Best Effort Medium
  description: Best-effort instance with 2 cores and 8Gi memory (Tanzu best-effort-medium)
  enabled: true
  default: false
  category: Standard
  cpu:
    cores: 2
    sockets: 1
    threads: 1
  memory:
    quantity: 8Gi
  machineProviders: []
