//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPAllocationConfig) DeepCopyInto(out *DHCPAllocationConfig) {
	*out = *in
	if in.RequireClientClasses != nil {
		in, out := &in.RequireClientClasses, &out.RequireClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPAllocationConfig.
func (in *DHCPAllocationConfig) DeepCopy() *DHCPAllocationConfig {
	if in == nil {
		return nil
	}
	out := new(DHCPAllocationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocation) DeepCopyInto(out *IPAllocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocation.
func (in *IPAllocation) DeepCopy() *IPAllocation {
	if in == nil {
		return nil
	}
	out := new(IPAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPAllocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocationList) DeepCopyInto(out *IPAllocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocationList.
func (in *IPAllocationList) DeepCopy() *IPAllocationList {
	if in == nil {
		return nil
	}
	out := new(IPAllocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPAllocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocationSpec) DeepCopyInto(out *IPAllocationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocationSpec.
func (in *IPAllocationSpec) DeepCopy() *IPAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(IPAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocationStatus) DeepCopyInto(out *IPAllocationStatus) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocationStatus.
func (in *IPAllocationStatus) DeepCopy() *IPAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(IPAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocationSummary) DeepCopyInto(out *IPAllocationSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocationSummary.
func (in *IPAllocationSummary) DeepCopy() *IPAllocationSummary {
	if in == nil {
		return nil
	}
	out := new(IPAllocationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualProvisioningConfig) DeepCopyInto(out *ManualProvisioningConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualProvisioningConfig.
func (in *ManualProvisioningConfig) DeepCopy() *ManualProvisioningConfig {
	if in == nil {
		return nil
	}
	out := new(ManualProvisioningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NAMProvisioningConfig) DeepCopyInto(out *NAMProvisioningConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NAMProvisioningConfig.
func (in *NAMProvisioningConfig) DeepCopy() *NAMProvisioningConfig {
	if in == nil {
		return nil
	}
	out := new(NAMProvisioningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNamespace) DeepCopyInto(out *NetworkNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNamespace.
func (in *NetworkNamespace) DeepCopy() *NetworkNamespace {
	if in == nil {
		return nil
	}
	out := new(NetworkNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNamespaceIPAllocation) DeepCopyInto(out *NetworkNamespaceIPAllocation) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticIPAllocationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(DHCPAllocationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNamespaceIPAllocation.
func (in *NetworkNamespaceIPAllocation) DeepCopy() *NetworkNamespaceIPAllocation {
	if in == nil {
		return nil
	}
	out := new(NetworkNamespaceIPAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNamespaceList) DeepCopyInto(out *NetworkNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNamespaceList.
func (in *NetworkNamespaceList) DeepCopy() *NetworkNamespaceList {
	if in == nil {
		return nil
	}
	out := new(NetworkNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNamespaceSpec) DeepCopyInto(out *NetworkNamespaceSpec) {
	*out = *in
	if in.NetworkProvisioning != nil {
		in, out := &in.NetworkProvisioning, &out.NetworkProvisioning
		*out = new(NetworkProvisioning)
		(*in).DeepCopyInto(*out)
	}
	if in.IPAllocation != nil {
		in, out := &in.IPAllocation, &out.IPAllocation
		*out = new(NetworkNamespaceIPAllocation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNamespaceSpec.
func (in *NetworkNamespaceSpec) DeepCopy() *NetworkNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNamespaceStatus) DeepCopyInto(out *NetworkNamespaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Created.DeepCopyInto(&out.Created)
	if in.AssociatedKubernetesClusterIDs != nil {
		in, out := &in.AssociatedKubernetesClusterIDs, &out.AssociatedKubernetesClusterIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPAllocationSummary != nil {
		in, out := &in.IPAllocationSummary, &out.IPAllocationSummary
		*out = new(IPAllocationSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNamespaceStatus.
func (in *NetworkNamespaceStatus) DeepCopy() *NetworkNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProvisioning) DeepCopyInto(out *NetworkProvisioning) {
	*out = *in
	if in.NAM != nil {
		in, out := &in.NAM, &out.NAM
		*out = new(NAMProvisioningConfig)
		**out = **in
	}
	if in.Manual != nil {
		in, out := &in.Manual, &out.Manual
		*out = new(ManualProvisioningConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProvisioning.
func (in *NetworkProvisioning) DeepCopy() *NetworkProvisioning {
	if in == nil {
		return nil
	}
	out := new(NetworkProvisioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticIPAllocationConfig) DeepCopyInto(out *StaticIPAllocationConfig) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticIPAllocationConfig.
func (in *StaticIPAllocationConfig) DeepCopy() *StaticIPAllocationConfig {
	if in == nil {
		return nil
	}
	out := new(StaticIPAllocationConfig)
	in.DeepCopyInto(out)
	return out
}
